export const PROJECT_DATA = [
  {
    project_name: "Kaizen Daily",
    project_description:
      "Kaizen Daily is a full-stack SaaS life operating system inspired by Japanese philosophy — blending habit tracking, daily journaling, mindful finance, and weekly reflection into one focused practice. Built around kaizen (continuous improvement), hansei (honest self-reflection), wabi-sabi (beauty in imperfection), and ikigai (reason for being). Features include a 3-habit Kaizen rule, a don't-break-the-chain calendar, streak recovery, focus mode, daily journal with mood tracking, weekly and monthly reviews, a spending tracker with budget categories, and a Journey page with lifetime stats, habit-mood correlations, and weekly score trends. Installable as a Progressive Web App on any device.",
    project_image: "/portfolio/images/kaizen/kaizen.PNG",
    tag: "web",
    link: "https://kaizen-daily.vercel.app/",
    linkType: "website",
    images: [
      "/portfolio/images/kaizen/kaizen-1.PNG",
      "/portfolio/images/kaizen/kaizen-2.PNG",
      "/portfolio/images/kaizen/kaizen-3.PNG",
      "/portfolio/images/kaizen/kaizen-4.PNG",
      "/portfolio/images/kaizen/kaizen-5.PNG",
      "/portfolio/images/kaizen/kaizen-6.PNG",
      "/portfolio/images/kaizen/kaizen-7.PNG",
      "/portfolio/images/kaizen/kaizen-8.PNG",
    ],
    technologies: [
      "React Router v7",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Neon",
      "Vercel",
      "Stripe",
      "Resend",
      "TailwindCSS",
      "Node.js",
    ],
    role: "Sole Developer & Designer",
    responsibilities: [
      "Architected and built the complete full-stack SaaS application from scratch — React Router v7 (SSR mode), Prisma ORM, Neon serverless PostgreSQL, and Vercel serverless functions",
      "Designed the entire UI system from the ground up — including design tokens, Japanese-inspired typography (Fraunces + Inter), bilingual i18n (English/Japanese), and all reusable UI components",
      "Built advanced habit tracking with streak recovery, rest days, keystone habit designation, quantity-based habits (e.g. 8 glasses of water), and a don't-break-the-chain calendar visualization",
      "Implemented a daily reflection journal featuring mood tracking, gratitude prompts, rotating reflection questions, and habit-mood correlation analytics to surface behavioral insights",
      "Developed weekly and monthly review system with composite scoring, sparkline trend charts, and self-evaluation workflows to support continuous improvement",
      "Created Focus Mode — a full-screen, distraction-free habit check-in experience supporting both binary and quantity-based habit completion",
      "Integrated Stripe for subscription billing with monthly and yearly plans, a 3-month free trial, webhook handling, and server-side plan enforcement",
      "Built a transactional email system using Resend for morning reminders, evening check-ins, weekly summaries, and user feedback notifications",
      "Implemented full PWA support with a service worker, web manifest, and home screen installation for an app-like experience on any device",
      "Shipped complete SEO infrastructure — sitemap.xml, robots.txt, Open Graph image meta, structured data, and noindex guards on all authenticated routes",
    ],
  },
  {
    project_name: "Powerhouse Church Website",
    project_description:
      "A full-featured church website for Powerhouse Church Christian Fellowship Intl., a growing congregation based in Cabuyao City, Laguna. The site serves as the church's digital home — featuring service schedules, location details, a YouTube-integrated sermons section, upcoming events, ministry pages, and a dedicated 'Visit Us' page. Designed to help the church connect with existing members and warmly welcome first-time visitors online.",
    project_image: "/portfolio/images/pcf/pcf.PNG",
    tag: "web",
    link: "https://powerhouse-church.vercel.app/",
    linkType: "website",
    images: [
      "/portfolio/images/pcf/pcf-1.PNG",
      "/portfolio/images/pcf/pcf-2.PNG",
      "/portfolio/images/pcf/pcf-3.PNG",
      "/portfolio/images/pcf/pcf-4.PNG",
      "/portfolio/images/pcf/pcf-5.PNG",
      "/portfolio/images/pcf/pcf-6.PNG",
    ],
    technologies: ["Next.js", "TailwindCSS", "TypeScript", "YouTube API", "Vercel"],
    role: "Full Stack Developer",
    responsibilities: [
      "Designed and built the complete church website from scratch, handling both UI design and front-end development",
      "Integrated the YouTube Data API to dynamically display the latest sermons and preaching content without manual updates",
      "Built an events page and ministry section to keep the congregation informed about upcoming activities and church programs",
      "Created a 'Visit Us' page with embedded Google Maps, service schedule details, and directions to lower the barrier for first-time visitors",
      "Designed a fully responsive layout optimized for both mobile and desktop, ensuring accessibility across all device types",
      "Deployed to Vercel with custom domain configuration and optimized build settings for fast page loads",
    ],
  },
  {
    project_name: "JFAAC Katsutadai Church Website",
    project_description:
      "A bilingual church website for JFAAC Katsutadai, a Full Gospel Church located in Yachiyo, Chiba, Japan. The site serves as the church's online presence for the local Japanese community — providing congregation info, service schedules, ministry details, upcoming events, sermon videos, and contact information. Built to bridge the church's reach between existing members and new visitors in Japan.",
    project_image: "/portfolio/images/jfaac/jfaac.PNG",
    tag: "web",
    link: "https://jfaac-katsutadai.vercel.app/",
    linkType: "website",
    images: [
      "/portfolio/images/jfaac/jfaac-1.PNG",
      "/portfolio/images/jfaac/jfaac-2.PNG",
      "/portfolio/images/jfaac/jfaac-3.PNG",
      "/portfolio/images/jfaac/jfaac-4.PNG",
      "/portfolio/images/jfaac/jfaac-5.PNG",
      "/portfolio/images/jfaac/jfaac-6.PNG",
      "/portfolio/images/jfaac/jfaac-7.PNG",
    ],
    technologies: ["Next.js", "TailwindCSS", "TypeScript", "Vercel"],
    role: "Full Stack Developer",
    responsibilities: [
      "Designed and built the complete church website from scratch, tailored for a Japanese-speaking audience",
      "Created pages for congregation information, weekly service schedules, location details, and contact forms",
      "Built a sermons and preaching section with embedded video content for members to access messages online",
      "Developed events and ministries pages to keep the congregation informed about church activities and community programs",
      "Designed a fully responsive, mobile-first layout ensuring the site looks great on all screen sizes",
      "Deployed to Vercel with custom configuration and fast global CDN delivery for users in Japan",
    ],
  },
  {
    project_name: "Better Swing Trader Website",
    project_description:
      "Better Swing Trader is a full-featured web platform built exclusively for stock swing traders who demand precision. The platform provides data-driven insights for tracking and analyzing swing trading strategies — helping traders identify patterns in wins and losses, maximize returns, and refine their approach over time. Includes an AI chatbot assistant, an automated email notification system, a subscriber database, and a content-rich blog and guide section.",
    project_image: "/portfolio/images/bst-web-feature.PNG",
    tag: "web",
    link: "https://betterswingtrader.com",
    linkType: "website",
    images: [
      "/portfolio/images/bst-web/bst-web-feature.PNG",
      "/portfolio/images/bst-web/bst-features.PNG",
      "/portfolio/images/bst-web/bst-download.PNG",
      "/portfolio/images/bst-web/bst-blog.PNG",
      "/portfolio/images/bst-web/bst-contact.PNG",
      "/portfolio/images/bst-web/bst-about-us.PNG",
      "/portfolio/images/bst-web/bst-how-it-works.PNG",
      "/portfolio/images/bst-web/bst-pricing.PNG",
      "/portfolio/images/bst-web/bst-guide.PNG",
      "/portfolio/images/bst-web/bst-tips.PNG",
      "/portfolio/images/bst-web/bst-suggested.PNG",
    ],
    technologies: ["HTML", "TailwindCSS", "JavaScript", "PHP", "MySQL", "PHPMailer", "Zapier"],
    role: "Full Stack Developer",
    responsibilities: [
      "Designed and developed a fully responsive multi-page website covering features, pricing, how-it-works, blog, tips, guides, and contact sections",
      "Integrated an AI chatbot assistant via Zapier to enhance user engagement and provide instant answers to trading-related questions",
      "Designed and implemented a subscriber database in MySQL for managing email lists, trading updates, and newsletter campaigns",
      "Built an automated email notification system using PHPMailer and server-side Cron Jobs to deliver scheduled trading updates and alerts to subscribers",
      "Optimized all pages for performance, SEO, and cross-browser compatibility to maximize organic traffic and user retention",
    ],
  },
  {
    project_name: "Our Wedding Website",
    project_description:
      "A personal wedding website capturing every detail of our special day — from our love story, proposal, and prenup gallery to wedding details, venue information, and a live countdown timer. Guests can browse photo galleries from the original ceremony, prints, and wedding day itself, submit RSVPs, and share their own memories through a guest photo upload section. Built as a lasting digital keepsake for family and friends.",
    project_image: "/portfolio/images/wed-feature.PNG",
    tag: "web",
    link: "https://ronneljunnawedding.com/",
    linkType: "website",
    images: [
      "/portfolio/images/wed-feature.PNG",
      "/portfolio/images/wedding/wed-story.PNG",
      "/portfolio/images/wedding/wed-details.PNG",
      "/portfolio/images/wedding/wed-gallery.PNG",
      "/portfolio/images/wedding/wed-proposal.PNG",
      "/portfolio/images/wedding/wed-prenup.PNG",
      "/portfolio/images/wedding/wed-guest.PNG",
      "/portfolio/images/wedding/wed-orig.PNG",
      "/portfolio/images/wedding/wed-prints.PNG",
      "/portfolio/images/wedding/wed-day.PNG",
      "/portfolio/images/wedding/wed-rsvp.PNG",
    ],
    technologies: ["Next.js", "TailwindCSS", "TypeScript", "MySQL", "Supabase", "Cloudinary"],
    role: "Full Stack Developer",
    responsibilities: [
      "Built the complete wedding website from scratch, covering all pages including love story, wedding details, gallery, RSVP, and guest upload sections",
      "Implemented a guest photo upload feature using Cloudinary for optimized image storage, automatic formatting, and responsive delivery",
      "Built multi-gallery sections with categorized views for proposal, prenup, original ceremony, prints, and wedding day photos",
      "Created a live countdown timer component and a complete RSVP system backed by Supabase and MySQL for guest management",
      "Designed a fully responsive, mobile-first layout ensuring a beautiful experience for guests viewing on any device",
    ],
  },
  {
    project_name: "Better Swing Trader Mobile App",
    project_description:
      "Better Swing Trader (BST) is a mobile analytics app designed to help stock swing traders track, analyze, and continuously improve their trading performance. It provides clear insights into daily, weekly, and monthly gains and losses, evaluates the effectiveness of individual trading strategies, and helps traders identify patterns in wins and losses to support better risk management. BST allows traders to monitor individual trades or groups of stocks, compare performance across time periods, and refine their trading rules — all in one focused tool. Note: BST is not a trading platform or stock screener; it is a dedicated performance-tracking and analytics tool for swing trading.",
    project_image: "/portfolio/images/bst-feature.png",
    tag: "mobile",
    iosLink: "https://apps.apple.com/us/app/best-swing-trader/id6737796315",
    linkType: "ios",
    images: [
      "/portfolio/images/bst-app/bst-1.webp",
      "/portfolio/images/bst-app/bst-2.webp",
      "/portfolio/images/bst-app/bst-3.webp",
      "/portfolio/images/bst-app/bst-4.webp",
      "/portfolio/images/bst-app/bst-5.webp",
      "/portfolio/images/bst-app/bst-6.webp",
      "/portfolio/images/bst-app/bst-7.webp",
      "/portfolio/images/bst-app/bst-8.webp",
    ],
    technologies: ["React Native", "JavaScript", "MySQL", "AsyncStorage", "React Navigation"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed and published a cross-platform mobile app for iOS and Android using React Native",
      "Built trade entry and management system allowing users to log, categorize, and review individual stock trades",
      "Implemented data visualization for daily, weekly, and monthly gains and losses to help traders identify performance trends",
      "Created strategy evaluation tools enabling users to compare win/loss patterns across different trading rules and time periods",
      "Integrated REST API for real-time data sync and used AsyncStorage for offline-first local data persistence",
      "Built smooth navigation flows and an intuitive UI using React Navigation, optimized for quick data entry during active trading sessions",
    ],
  },
  {
    project_name: "Queue Management System",
    project_description:
      "A real-time Queue Management System (QMS) web application built for The Medical City South Luzon to optimize patient flow and reduce wait times across hospital departments. The system provides live queue updates, an admin control dashboard, department-specific queue windows, and detailed reporting — replacing manual queue management with a fully digital, real-time solution.",
    project_image: "/portfolio/images/tmcsl-qms/tmcsl-qms-9.PNG",
    tag: "web",
    link: "#",
    images: [
      "/portfolio/images/tmcsl-qms/tmcsl-qms.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-1.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-2.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-3.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-4.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-5.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-6.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-7.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-8.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-9.PNG",
      "/portfolio/images/tmcsl-qms/tmcsl-qms-10.PNG",
    ],
    technologies: ["HTML", "CSS", "PHP", "JavaScript", "MySQL", "Socket.io"],
    role: "Full Stack Developer",
    responsibilities: [
      "Designed and developed a real-time queue management web application to streamline patient flow across hospital departments",
      "Implemented WebSocket communication using Socket.io for live queue updates — ensuring patients and staff see number changes instantly without page refresh",
      "Built an admin dashboard for queue control, including the ability to call, skip, transfer, and reset queue numbers per department",
      "Created department-specific queue display windows designed for public screens in waiting areas",
      "Developed a reporting and analytics module to track daily queue volumes, average wait times, and service performance per department",
      "Integrated RESTful APIs to connect the front-end queue interface with the back-end PHP and MySQL data layer",
    ],
  },
  {
    project_name: "Meal Monitoring System",
    project_description:
      "A web-based Meal Monitoring System built for The Medical City South Luzon to digitize and streamline employee meal management. Staff can claim meals quickly using a barcode scanner, eliminating manual tracking. The system includes real-time data filtering, detailed consumption reports, and one-click Excel export — giving administrators full visibility into meal usage across departments.",
    project_image: "/portfolio/images/meal-feature.png",
    tag: "web",
    link: "#",
    images: ["/portfolio/images/meal-feature.png"],
    technologies: ["PHP", "JavaScript", "Laravel", "Node.js", "Express", "MySQL"],
    role: "Full Stack Developer",
    responsibilities: [
      "Designed and built the complete web application for employee meal tracking and management",
      "Developed barcode scanning functionality to enable fast, error-free meal claims at meal stations",
      "Built a reporting system with Excel export, allowing administrators to extract meal consumption data by date, department, or employee",
      "Implemented advanced filtering and search features so managers can quickly slice and analyze meal data by multiple parameters",
      "Developed the back-end API layer using Laravel and Node.js/Express with MySQL for efficient data storage and retrieval",
      "Designed a clean, user-friendly admin interface to minimize training time for hospital staff",
    ],
  },
  {
    project_name: "The Medical City South Luzon SOL APP",
    project_description:
      "The TMCSL SOL mobile app is a patient-facing healthcare application for The Medical City South Luzon, built to streamline the hospital experience from a smartphone. Patients and medical professionals can manage appointments, view lab results, and handle billing transactions — all integrated directly with the hospital's core HIS/EMR system for accurate, real-time data.",
    project_image: "/portfolio/images/sol-feature.png",
    tag: "mobile",
    link: "#",
    images: [
      "/portfolio/images/sol-feature.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-00.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-1.png",
      "/portfolio/images/tmcsl-app/tmcsl-app.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-2.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-4.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-5.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-6.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-7.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-8.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-9.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-10.png",
      "/portfolio/images/tmcsl-app/tmcsl-app-11.png",
    ],
    technologies: ["Flutter", "Dart", "MySQL", "REST API", "PHP"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed a cross-platform healthcare mobile application using Flutter (Dart), integrated with the hospital's core HIS/EMR system via REST APIs",
      "Implemented secure authentication and role-based authorization to protect sensitive patient health data",
      "Built an appointment scheduling system allowing patients to book, view, and manage hospital appointments directly from their phones",
      "Integrated a lab results viewing feature providing patients with real-time access to their test results and health records",
      "Integrated billing and payment transaction APIs enabling patients to view statements and handle payments within the app",
      "Implemented push notifications via OneSignal for appointment reminders, lab result alerts, and system updates",
    ],
  },
  {
    project_name: "SSC - For Online SST Customers",
    project_description:
      "SSC is a customer-facing mobile app that enables shoppers of small retail stores to browse products and place orders directly from their smartphones. Seamlessly integrated with the SST point-of-sale system, SSC bridges online ordering with in-store POS management — giving store owners real-time order visibility while providing customers a convenient, ad-free shopping experience from home.",
    project_image: "/portfolio/images/ssc-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.sst_customer",
    linkType: "android",
    images: [
      "/portfolio/images/ssc-app/ssc-1.png",
      "/portfolio/images/ssc-app/ssc-2.png",
      "/portfolio/images/ssc-app/ssc-3.png",
      "/portfolio/images/ssc-app/ssc-4.png",
      "/portfolio/images/ssc-app/ssc-5.png",
    ],
    technologies: ["React Native", "JavaScript", "MySQL", "React Navigation"],
    role: "Mobile Developer",
    responsibilities: [
      "Built a customer-facing React Native mobile app for online product browsing and order placement, published on the Google Play Store",
      "Implemented product catalog browsing with search, category filtering, and detailed product information views",
      "Created a complete order placement and tracking system — from cart to order confirmation — integrated with the SST POS back-end",
      "Integrated real-time order status notifications to keep customers informed from order placement to fulfillment",
      "Designed an intuitive, ad-free UI optimized for quick browsing and one-tap ordering on Android devices",
    ],
  },
  {
    project_name: "SST, Sari Sari iPOS Terminal",
    project_description:
      "SST (Sari Sari iPOS Terminal) transforms any Android smartphone or tablet into a full-featured point-of-sale system for small retail and convenience stores. It supports barcode scanning, manual product entry, inventory management, and automated calculations for totals, taxes, and change. The app tracks complete sales history, generates business reports, and supports multi-user access across devices — making it an efficient and accessible POS solution for small-scale retail operations.",
    project_image: "/portfolio/images/sst-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.sst",
    linkType: "android",
    images: [
      "/portfolio/images/sst-app/sst-1.png",
      "/portfolio/images/sst-app/sst-2.png",
      "/portfolio/images/sst-app/sst-3.png",
      "/portfolio/images/sst-app/sst-4.png",
      "/portfolio/images/sst-app/sst-5.png",
    ],
    technologies: ["React Native", "JavaScript", "MySQL"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed and published a full-featured POS mobile application for small retail stores on the Google Play Store",
      "Implemented barcode scanning for fast product lookup and checkout, with fallback manual entry for items without barcodes",
      "Built a complete inventory management system with stock tracking, product categories, and low-stock alerts",
      "Created a sales tracking and reporting system giving store owners visibility into daily, weekly, and monthly revenue",
      "Designed an offline-first architecture with local data sync, ensuring the app works reliably even without an internet connection",
      "Implemented multi-user support allowing multiple staff members to operate the POS across different devices",
    ],
  },
  {
    project_name: "Cash Expense Tracker",
    project_description:
      "Cash Expense Tracker (XPTracker) is a mobile app that helps individuals and households track daily expenses and manage cash spending with clarity. Users can quickly log expenses, assign categories, and view spending summaries by day, week, month, or year — with calendar views, detailed reports, and visual breakdowns. The app supports receipt scanning, automatic cloud backups, Excel export, and multiple user profiles, making it ideal for anyone who wants a clear picture of where their money goes.",
    project_image: "/portfolio/images/xpt-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.cxptracker",
    linkType: "android",
    images: [
      "/portfolio/images/xptracker-app/xpt-1.png",
      "/portfolio/images/xptracker-app/xpt-2.png",
      "/portfolio/images/xptracker-app/xpt-3.png",
      "/portfolio/images/xptracker-app/xpt-4.png",
      "/portfolio/images/xptracker-app/xpt-5.png",
      "/portfolio/images/xptracker-app/xpt-6.png",
      "/portfolio/images/xptracker-app/xpt-7.png",
    ],
    technologies: ["React Native", "JavaScript", "AsyncStorage", "Excel Export", "Cloud Backup"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed and published a comprehensive expense tracking mobile app on the Google Play Store",
      "Implemented automatic cloud backup functionality to protect user data across device changes and reinstalls",
      "Built an expense categorization and tagging system allowing users to organize spending by custom categories",
      "Created an Excel export feature enabling users to extract expense data for budgeting, reporting, or sharing with accountants",
      "Designed data visualizations — charts, calendar heatmaps, and trend graphs — to surface clear insights into spending patterns",
      "Built multi-user profile support so households can track individual and combined expenses separately",
    ],
  },
  {
    project_name: "Task and Reward Tracker",
    project_description:
      "Task and Reward Tracker is a gamified task management app for families and teams. A Primary User (such as a parent or manager) can create and assign tasks, set token values per task, and monitor completion in real time through notifications, calendars, and task lists. Dependents complete tasks to earn tokens redeemable for monetary value or custom rewards — all tracked automatically. The app supports recurring tasks, multiple user profiles, and real-time updates, making responsibility and motivation measurable and fun.",
    project_image: "/portfolio/images/trt-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.trt",
    iosLink: "https://apps.apple.com/us/app/task-and-reward-tracker/id1566847771",
    linkType: "both",
    images: [
      "/portfolio/images/trt-app/trt-1.webp",
      "/portfolio/images/trt-app/trt-2.webp",
      "/portfolio/images/trt-app/trt-3.webp",
      "/portfolio/images/trt-app/trt-4.webp",
      "/portfolio/images/trt-app/trt-5.webp",
      "/portfolio/images/trt-app/trt-6.webp",
      "/portfolio/images/trt-app/trt-7.webp",
    ],
    technologies: ["React Native", "JavaScript", "Push Notifications", "AsyncStorage"],
    role: "Mobile Developer",
    responsibilities: [
      "Built and published a gamified task management application for iOS and Android using React Native",
      "Implemented a token-based reward system where task completion earns redeemable points, with Primary User approval/rejection controls",
      "Created a real-time push notification system to alert dependents of new task assignments and remind Primary Users of pending approvals",
      "Developed recurring task scheduling with support for daily, weekly, and custom repeat intervals",
      "Built reporting and analytics features giving Primary Users a clear overview of task completion rates, token balances, and individual performance over time",
      "Designed an intuitive multi-profile UI allowing seamless switching between Primary User and dependent views",
    ],
  },
  {
    project_name: "Caregiver Assistant",
    project_description:
      "Caregiver Assistant is a mobile health tracking app designed to help caregivers and families monitor and share vital signs for patients or loved ones. Users can log temperature, blood pressure, heart rate, glucose levels, weight, pain levels, and more — with reminders, notifications, and historical trend tracking to support informed follow-ups with healthcare professionals. The app supports secure real-time data sharing between caregivers and patients, multiple patient profiles, and unlimited vitals — making it suitable for both personal caregiving and professional use.",
    project_image: "/portfolio/images/cga-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.caregiverassistant",
    iosLink: "https://apps.apple.com/us/app/ca-caregiver-assistant/id1608863934",
    linkType: "both",
    images: [
      "/portfolio/images/cga-app/cga-1.webp",
      "/portfolio/images/cga-app/cga-2.webp",
      "/portfolio/images/cga-app/cga-3.webp",
      "/portfolio/images/cga-app/cga-4.webp",
      "/portfolio/images/cga-app/cga-5.webp",
      "/portfolio/images/cga-app/cga-6.webp",
      "/portfolio/images/cga-app/cga-7.webp",
      "/portfolio/images/cga-app/cga-8.webp",
    ],
    technologies: ["React Native", "JavaScript", "Chart Libraries", "AsyncStorage"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed and published a cross-platform healthcare tracking application for iOS and Android using React Native",
      "Built a comprehensive vital signs recording system supporting temperature, blood pressure, heart rate, glucose, weight, pain, and custom vitals",
      "Implemented secure real-time data sharing between caregiver and patient accounts, with granular permission controls over who can view and enter data",
      "Created interactive data visualizations — line charts, trend graphs, and historical logs — to help caregivers and doctors identify abnormal readings and monitor long-term changes",
      "Built customizable reminder and notification system to ensure vitals are recorded consistently at scheduled times",
      "Implemented export and sharing functionality so caregivers can generate health reports to share with healthcare professionals",
    ],
  },
  {
    project_name: "Client Logger",
    project_description:
      "Client Logger is a business check-in app that enables restaurants, clinics, retail stores, and events to quickly and securely log customer visits using QR code scanning or manual form entry. Each visit creates a time-stamped record with contact details that can be used for operational tracking, customer communication, and marketing. The app also supports reservation management and optional SMS notifications — all without ads and across multiple devices.",
    project_image: "/portfolio/images/cl-feature.png",
    tag: "mobile",
    link: "#",
    images: [
      "/portfolio/images/cl-app/cl-1.png",
      "/portfolio/images/cl-app/cl-2.png",
      "/portfolio/images/cl-app/cl-3.png",
      "/portfolio/images/cl-app/cl-4.png",
      "/portfolio/images/cl-app/cl-5.png",
      "/portfolio/images/cl-app/cl-6.png",
      "/portfolio/images/cl-app/cl-7.png",
    ],
    technologies: ["React Native", "JavaScript", "SMS API", "Firebase", "QR Code"],
    role: "Mobile Developer",
    responsibilities: [
      "Built a business client check-in application using React Native with QR code scanning and manual entry support",
      "Implemented QR code generation and scanning to instantly capture and log customer contact information without manual forms",
      "Integrated an SMS notification system to send visit confirmations and reservation reminders to customers automatically",
      "Created a reservation management system allowing businesses to schedule, track, and manage customer bookings",
      "Built Firebase-backed real-time data storage and sync so visit logs are instantly available across multiple staff devices",
      "Designed a clean business-facing UI with visit history, customer records, and export capabilities for follow-up campaigns",
    ],
  },
  {
    project_name: "Entry Logger",
    project_description:
      "Entry Logger is a companion app to Client Logger that lets individuals generate a personalized QR code containing their selected contact information — name, phone number, and more. By simply displaying their QR code at any participating establishment, users can log their entry instantly without filling out manual forms. The app gives users full control over what data is shared, supports printable QR codes, and tracks a personal history of all visited locations and events.",
    project_image: "/portfolio/images/el-feature.png",
    tag: "mobile",
    androidLink: "https://webcoastserver.com/entrylogger/downloads/",
    linkType: "android",
    images: [
      "/portfolio/images/el-app/el-1.png",
      "/portfolio/images/el-app/el-2.png",
      "/portfolio/images/el-app/el-3.png",
      "/portfolio/images/el-app/el-4.png",
      "/portfolio/images/el-app/el-5.png",
    ],
    technologies: ["React Native", "JavaScript", "QR Code Library", "AsyncStorage"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed a QR code generation app for Android that creates personalized, scannable contact QR codes for fast venue check-ins",
      "Implemented secure data encoding to embed user-selected contact information into QR codes with privacy controls",
      "Built user profile and information management screens, allowing users to customize what details appear in their QR code",
      "Created QR code scanning and validation logic for use alongside the Client Logger business app",
      "Implemented a visit history log using AsyncStorage so users can track all locations and events they've checked into",
      "Added printable QR code support so users can display their code on paper at locations without phone access",
    ],
  },
  {
    project_name: "Budgetfy",
    project_description:
      "Budgetfy is a native Android app that helps users take control of their personal finances through simple, fast expense and income tracking. Users can log transactions quickly, assign categories, and get a clear picture of their spending habits through daily, weekly, and monthly breakdowns — backed by visual graphs and detailed reports. Designed for everyday use with a clean Material Design interface that makes budgeting approachable for anyone.",
    project_image: "/portfolio/images/bf-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=budgetfy.arsoft.com",
    linkType: "android",
    images: [
      "/portfolio/images/budget-app/budget-1.webp",
      "/portfolio/images/budget-app/budget-2.webp",
      "/portfolio/images/budget-app/budget-3.webp",
      "/portfolio/images/budget-app/budget-4.webp",
      "/portfolio/images/budget-app/budget-5.webp",
      "/portfolio/images/budget-app/budget-6.webp",
    ],
    technologies: ["Java", "Android SDK", "SQLite", "MPAndroidChart", "Material Design"],
    role: "Android Developer",
    responsibilities: [
      "Developed and published a native Android budget tracking app using Java and the Android SDK",
      "Implemented a local SQLite database for fast, offline-first transaction storage and retrieval with zero latency",
      "Created interactive data visualizations using MPAndroidChart — including bar charts, pie charts, and line graphs — to surface spending trends at a glance",
      "Built a flexible filtering and reporting system allowing users to analyze transactions by day, week, month, or custom date range",
      "Designed a clean, intuitive Material Design UI focused on fast data entry and minimal friction for daily use",
      "Implemented expense categorization, running totals, and budget threshold alerts to help users stay on track",
    ],
  },
  {
    project_name: "Web Coast Apps",
    project_description:
      "The official company website for Web Coast Apps — a mobile app development company focused on building practical tracking, reporting, and productivity applications. The site showcases the company's portfolio of published apps, highlights key features and use cases, and provides download links and contact information for potential clients and app users.",
    project_image: "/portfolio/images/wca-web/web-1.PNG",
    tag: "web",
    link: "https://webcoastapps.com/",
    linkType: "website",
    images: [
      "/portfolio/images/wca-web/web-1.PNG",
      "/portfolio/images/wca-web/web-2.PNG",
      "/portfolio/images/wca-web/web-3.PNG",
      "/portfolio/images/wca-web/web-4.PNG",
      "/portfolio/images/wca-web/web-5.PNG",
      "/portfolio/images/wca-web/web-6.PNG",
      "/portfolio/images/wca-web/web-7.PNG",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    role: "Frontend Developer",
    responsibilities: [
      "Designed and developed the company showcase website from scratch, presenting the full app portfolio in a clean, professional layout",
      "Created fully responsive layouts for desktop, tablet, and mobile — ensuring a consistent experience across all devices",
      "Built dedicated app presentation sections highlighting each product's key features, screenshots, and download links",
      "Implemented a contact section and app download CTAs to convert site visitors into users and business leads",
      "Optimized page performance and cross-browser compatibility for maximum reach across all major browsers",
    ],
  },
  {
    project_name: "Performance Evaluation Manager",
    project_description:
      "Performance Evaluation Manager (PEM) is a mobile app that helps managers and employees capture and track performance evaluations between formal review cycles. Using predefined, weighted questions and categories, evaluations become measurable and comparable over time. The app supports both manager-led and self-evaluations, helping users document achievements, track recurring issues, and monitor progress toward goals throughout the year — making formal reviews faster, fairer, and more data-driven. Available on both iOS and Android.",
    project_image: "/portfolio/images/pem-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.pem",
    iosLink: "https://apps.apple.com/us/app/performance-evaluation-manager/id1516410882",
    linkType: "both",
    images: [
      "/portfolio/images/pem-app/pem-1.webp",
      "/portfolio/images/pem-app/pem-2.webp",
      "/portfolio/images/pem-app/pem-3.webp",
      "/portfolio/images/pem-app/pem-4.webp",
      "/portfolio/images/pem-app/pem-5.webp",
    ],
    technologies: ["React Native", "JavaScript", "Firebase", "AsyncStorage"],
    role: "Mobile Developer",
    responsibilities: [
      "Built and published a cross-platform employee evaluation app for iOS and Android using React Native",
      "Implemented a weighted evaluation form system with predefined question categories, rating scales, and scoring logic to make performance measurable",
      "Created both manager-led evaluation and self-evaluation workflows, allowing two-sided performance documentation",
      "Built employee performance tracking with historical records, allowing managers to compare evaluations over time and identify growth or recurring issues",
      "Developed reporting and analytics features that aggregate ratings and notes into clear summaries to support formal performance reviews",
      "Integrated Firebase for optional remote backup and data security, with a demo mode for first-time onboarding",
    ],
  },
  {
    project_name: "Tipsee Elite",
    project_description:
      "TipSee Elite is a fast, lightweight, and completely ad-free tip tracking app for servers, delivery drivers, stylists, and any professional who earns tips. Users can quickly log cash and card tips, track wages and tip-outs, and view earnings through daily, weekly, monthly, and yearly summaries. Built to run entirely locally for maximum speed — no account or cloud setup required. Includes calendar-based tracking, personalized notes, automatic backups, and is fully free to use. Available on both iOS and Android.",
    project_image: "/portfolio/images/te-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.tipseelite",
    iosLink: "https://apps.apple.com/us/app/tipsee-elite/id1535149595",
    linkType: "both",
    images: [
      "/portfolio/images/tip-elite-app/tip-elite-1.webp",
      "/portfolio/images/tip-elite-app/tip-elite-2.webp",
      "/portfolio/images/tip-elite-app/tip-elite-3.webp",
      "/portfolio/images/tip-elite-app/tip-elite-4.webp",
      "/portfolio/images/tip-elite-app/tip-elite-5.webp",
      "/portfolio/images/tip-elite-app/tip-elite-6.webp",
      "/portfolio/images/tip-elite-app/tip-elite-7.webp",
    ],
    technologies: ["React Native", "JavaScript", "Chart Libraries", "AsyncStorage"],
    role: "Mobile Developer",
    responsibilities: [
      "Developed and published a cross-platform tip tracking app for iOS and Android using React Native",
      "Implemented fast tip entry with support for cash, card, wage, and tip-out logging — optimized for quick input at end of shift",
      "Built calendar-based tracking and daily/weekly/monthly/yearly earnings summaries with running totals and averages",
      "Created pattern analysis and data visualization using chart libraries to surface earning trends over time",
      "Built comparison features allowing users to compare earnings across weeks, months, and years at a glance",
      "Implemented automatic local backup using AsyncStorage, ensuring no data is lost across app updates or device restarts",
    ],
  },
  {
    project_name: "Tipsee",
    project_description:
      "TipSee is a comprehensive tip and income tracking app for tipped workers, gig professionals, and independent contractors — built and continuously improved over more than a decade. Users can log tips, wages, commissions, and expenses across multiple jobs in one platform, with automatic income calculations, detailed weekly/monthly/yearly reports, and visual trend charts. Advanced features include client-based tip tracking, receipt photo attachments, home screen widgets, income goal setting, scheduled reminders, and secure data export — making it a complete income management solution for anyone with variable earnings.",
    project_image: "/portfolio/images/ts-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.wca.tipsee",
    linkType: "android",
    images: [
      "/portfolio/images/tip-app/tip-1.webp",
      "/portfolio/images/tip-app/tip-2.webp",
      "/portfolio/images/tip-app/tip-3.webp",
      "/portfolio/images/tip-app/tip-4.webp",
      "/portfolio/images/tip-app/tip-5.webp",
      "/portfolio/images/tip-app/tip-6.webp",
      "/portfolio/images/tip-app/tip-7.webp",
    ],
    technologies: ["Java", "Android SDK", "SQLite", "MPAndroidChart"],
    role: "Android Developer",
    responsibilities: [
      "Developed and published a comprehensive native Android tip and income tracking app built with Java and the Android SDK",
      "Implemented a local SQLite database for fast, reliable offline-first storage of tips, wages, commissions, and expense records",
      "Created detailed charts and graphs using MPAndroidChart for daily, weekly, monthly, and yearly tip analysis and earnings trends",
      "Built multi-job support allowing users to track income from multiple employers or gigs simultaneously within a single app",
      "Implemented export and backup functionality so users can securely save and share their income data for financial analysis or tax purposes",
      "Continuously maintained and improved the app over multiple years based on user feedback, adding new features and fixing compatibility issues with new Android versions",
    ],
  },
  {
    project_name: "Medicine Scheduler and Tracker",
    project_description:
      "Medicine Scheduler and Tracker (MST) is a medication management app that helps users reliably schedule, track, and record medication intake through timely alarm notifications. Users can log taken or missed medications, view past and upcoming schedules on a calendar, and compare actual intake times against scheduled times — all without medical advice or intervention. Key features include customizable reminders with optional voice alerts, flexible scheduling (hourly, multiple doses, or meal-based timing), multiple user profiles, and a summary dashboard for daily medication awareness. Available on both iOS and Android.",
    project_image: "/portfolio/images/mst-feature.png",
    tag: "mobile",
    androidLink: "https://play.google.com/store/apps/details?id=com.medicinest",
    iosLink: "https://apps.apple.com/us/app/medicine-tracker-and-scheduler/id1296334224",
    linkType: "both",
    images: [
      "/portfolio/images/mst-app/mst-1.webp",
      "/portfolio/images/mst-app/mst-2.webp",
      "/portfolio/images/mst-app/mst-3.webp",
      "/portfolio/images/mst-app/mst-4.webp",
      "/portfolio/images/mst-app/mst-5.webp",
      "/portfolio/images/mst-app/mst-6.webp",
    ],
    technologies: ["Java", "Android SDK", "SQLite", "Alarm Manager", "Notifications"],
    role: "Android Developer",
    responsibilities: [
      "Built and published a cross-platform medication scheduling and tracking app for iOS and Android",
      "Implemented a customizable medication reminder system using Android Alarm Manager with support for voice alerts, vibration, and silent modes",
      "Created flexible scheduling options — including hourly intervals, multiple doses within time ranges, and meal-based timing (breakfast, lunch, dinner, bedtime)",
      "Developed a calendar view displaying taken and scheduled medications at a glance, with color-coded status indicators for taken, missed, and upcoming doses",
      "Built a summary dashboard comparing actual intake times to scheduled times for the previous, current, and next day to help users stay consistent",
      "Implemented multiple user profile support so the app can track medications for different family members, children, or patients from a single device",
    ],
  },
];