export const PROJECT_DATA = [
    {
    project_name: "Kaizen Daily",
    project_description: "Kaizen Daily is a personal life operating system inspired by Japanese philosophy — combining habit tracking, daily reflection, mindful finance, and weekly review into one focused practice. Built around kaizen (continuous improvement), hansei (honest self-reflection), wabi-sabi (beauty in imperfection), and ikigai (reason for being). Features include a 3-habit Kaizen rule, don't-break-the-chain calendar, streak recovery, focus mode, daily journal with mood tracking, weekly and monthly reviews, spending tracker with budget categories, and a Journey page with lifetime stats, habit-mood correlations, and weekly score trends. Available as a Progressive Web App — installable on any device.",
    project_image: "/portfolio/images/kaizen/kaizen.PNG",
    tag: "web",
    link: "https://kaizen-daily.vercel.app/",
    linkType: "website",
    images: [
        "/portfolio/images/kaizen/kaizen-1.PNG",
        "/portfolio/images/kaizen/kaizen-2.PNG",
        "/portfolio/images/kaizen/kaizen-3.PNG",
        "/portfolio/images/kaizen/kaizen-4.PNG",
        "/portfolio/images/kaizen/kaizen-5.PNG",
        "/portfolio/images/kaizen/kaizen-6.PNG",
        "/portfolio/images/kaizen/kaizen-7.PNG",
        "/portfolio/images/kaizen/kaizen-8.PNG",
    ],
    technologies: [
        "React Router v7",
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Neon",
        "Vercel",
        "Stripe",
        "Resend",
        "TailwindCSS",
        "Node.js",
    ],
    role: "Sole Developer & Designer",
    responsibilities: [
        "Architected and built the full-stack SaaS app from scratch — React Router v7, Prisma, Neon (serverless Postgres), and Vercel serverless",
        "Designed the complete UI system including design tokens, Japanese-inspired typography (Fraunces + Inter), bilingual i18n (English/Japanese), and all UI components",
        "Built habit tracking with streak recovery, rest days, keystone habit designation, quantity habits (e.g. 8 glasses of water), and a don't-break-the-chain calendar",
        "Implemented daily reflection journal with mood tracking, gratitude, rotating prompts, and habit-mood correlation analytics",
        "Developed weekly and monthly review system with composite scoring, sparkline trends, and self-evaluation",
        "Created Focus Mode — a full-screen distraction-free habit check-in with binary and quantity habit support",
        "Integrated Stripe for subscription billing (monthly and yearly plans) with a 3-month free trial",
        "Built email notification system using Resend for morning reminders, evening check-ins, weekly summaries, and user feedback",
        "Implemented PWA support with service worker, manifest, and home screen installation",
        "Designed and shipped SEO infrastructure including sitemap, robots.txt, OG image meta, and noindex on authenticated routes",
    ]
},
// {
//     project_name: "Affiliate Kit",
//     project_description: "Affiliate Kit is a full-stack SaaS platform built for Southeast Asian affiliate marketers across the Philippines, Malaysia, Singapore, Indonesia, and Thailand. It lets buyers create their own branded affiliate storefront (affiliatekit.com/store/[username]) to showcase products from Shopee, Lazada, TikTok Shop, Temu, and Zalora — complete with built-in affiliate tools, a blog, click analytics, and a buyer dashboard. Features include an onboarding wizard, plan-gated features (Free / Pro / Business), Stripe billing, Cloudinary image uploads, and transactional emails via Resend.",
//     project_image: "/portfolio/images/affiliate-kit/affiliate-kit-feature.png",
//     tag: "web",
//     link: "https://affiliate-kit.vercel.app/",
//     linkType: "website",
//     images: [
//         "/portfolio/images/affiliate-kit/affiliate-kit-feature.png",
//     ],
//     technologies: [
//         "React Router v7",
//         "TypeScript",
//         "Prisma",
//         "PostgreSQL",
//         "TailwindCSS",
//         "Node.js",
//         "Stripe",
//         "Cloudinary",
//         "Resend",
//         "Vercel",
//     ],
//     role: "Full Stack Developer",
//     responsibilities: [
//         "Architected and built a full-stack multi-tenant SaaS platform using React Router v7 (framework/SSR mode) with path-based store routing (/store/[username])",
//         "Designed the complete Prisma schema covering Users, Stores, Products, Posts, ClickEvents, PlatformConnections, Sessions, and plan management",
//         "Built a 4-step onboarding wizard covering store identity, appearance customization, platform connections, and first product setup",
//         "Implemented cookie-based authentication with email verification, forgot password, and secure reset flow via Resend",
//         "Integrated Stripe Checkout and webhooks for Free / Pro / Business plan management with server-side feature gating on all loaders and actions",
//         "Developed the buyer dashboard with product manager, analytics (clicks, conversions, UTM breakdown), blog editor, platform connections, and billing page",
//         "Built five affiliate tools into the template storefront: Link Shortener, Commission Calculator, Hashtag Generator, Product Comparison Table, and UTM Link Builder",
//         "Implemented SSR SEO infrastructure including meta tags, Open Graph, Twitter Cards, JSON-LD structured data, sitemap.xml, and robots.txt",
//         "Integrated Cloudinary for image uploads with auto-format and responsive optimization across product images, store logos, and blog covers",
//         "Designed a reusable TailwindCSS component system including ProductCard, PricingCard, PlanGateBanner, UsageMeter, StepWizard, and DashboardSidebar",
//     ]
// },
{
    project_name: "Powerhouse Church Website",
    project_description: "A full-featured church website for Powerhouse Church Christian Fellowship Intl., a community-driven congregation based in Cabuyao City, Laguna. The site serves as a digital home for the church — featuring service schedules, location info, a YouTube-integrated sermons/preaching section, upcoming events, ministries, and a visit us page. Built to help the church connect with existing members and welcome new visitors online.",
    project_image: "/portfolio/images/pcf/pcf.PNG",
    tag: "web",
    link: "https://powerhouse-church.vercel.app/",
    linkType: "website",
    images: [
        "/portfolio/images/pcf/pcf-1.PNG",
        "/portfolio/images/pcf/pcf-2.PNG",
        "/portfolio/images/pcf/pcf-3.PNG",
        "/portfolio/images/pcf/pcf-4.PNG",
        "/portfolio/images/pcf/pcf-5.PNG",
        "/portfolio/images/pcf/pcf-6.PNG",
    ],
    technologies: ["Next.js", "TailwindCSS", "TypeScript", "YouTube API", "Vercel"],
    role: "Full Stack Developer",
    responsibilities: [
        "Designed and built the complete church website from scratch",
        "Integrated YouTube API to display latest sermons and preaching content dynamically",
        "Created events and ministries pages to keep the congregation informed",
        "Built a visit us page with Google Maps integration and service schedule details",
        "Designed responsive layout optimized for mobile and desktop",
        "Deployed to Vercel with custom domain configuration",
    ]
},
{
    project_name: "JFAAC Katsutadai Church Website",
    project_description: "A church website for JFAAC Katsutadai, a Full Gospel Church located in Yachiyo, Chiba, Japan. The site serves as the church's online presence — providing information about the congregation, service schedules, ministries, events, and how to connect. Designed to reach both existing members and new visitors in the local Japanese community.",
    project_image: "/portfolio/images/jfaac/jfaac.png",
    tag: "web",
    link: "https://jfaac-katsutadai.vercel.app/",
    linkType: "website",
    images: [
        "/portfolio/images/jfaac/jfaac-1.png",
        "/portfolio/images/jfaac/jfaac-2.png",
        "/portfolio/images/jfaac/jfaac-3.png",
        "/portfolio/images/jfaac/jfaac-4.png",
        "/portfolio/images/jfaac/jfaac-5.png",
        "/portfolio/images/jfaac/jfaac-6.png",
        "/portfolio/images/jfaac/jfaac-7.png",
    ],
    technologies: ["Next.js", "TailwindCSS", "TypeScript", "Vercel"],
    role: "Full Stack Developer",
    responsibilities: [
        "Designed and built the complete church website from scratch",
        "Created pages for church information, service schedules, and location details",
        "Built sermons/preaching section with video content integration",
        "Developed events and ministries pages for congregation updates",
        "Designed responsive layout optimized for mobile and desktop",
        "Deployed to Vercel with custom configuration",
    ]
},
    {
        project_name: "Better Swing Trader Website",
        project_description: 'Better Swing Trader is built exclusively for swing traders who demand precision. Track every trade, analyze your swing trading strategies, and maximize returns with data-driven insights that day traders and long-term investors miss.',
        project_image: "/portfolio/images/bst-web-feature.PNG",
        tag: "web",
        link: "https://betterswingtrader.com",
        linkType: "website",
        images: [
            "/portfolio/images/bst-web/bst-web-feature.PNG",
            "/portfolio/images/bst-web/bst-features.PNG",
            "/portfolio/images/bst-web/bst-download.PNG",
            "/portfolio/images/bst-web/bst-blog.PNG",
            "/portfolio/images/bst-web/bst-contact.PNG",
            "/portfolio/images/bst-web/bst-about-us.PNG",
            "/portfolio/images/bst-web/bst-how-it-works.PNG",
            "/portfolio/images/bst-web/bst-pricing.PNG",
            "/portfolio/images/bst-web/bst-guide.PNG",
            "/portfolio/images/bst-web/bst-tips.PNG",
            "/portfolio/images/bst-web/bst-suggested.PNG",
        ],
        technologies: ["HTML", "TailwindCSS", "JavaScript", "PHP", "MySQL", "PHPmailer", "Zapier"],
        role: "Full-stack Developer",
        responsibilities: [
            "Designed responsive layout for mobile and desktop",
            "Integration of an AI chatbot assistant via Zapier to enhance user engagement",
            "Design and implementation of a subscriber database for email notifications and trading updates",
            "Development of an automated email notification system using PHPMailer and Cron Job",
        ]
    },
    {
        project_name: "Our Wedding Website",
        project_description: 'Everything about our wedding day — from our love story and wedding details to the venue, countdown, and beautiful photo galleries. Guest can also share their own memories through the guest photo upload section.',
        project_image: "/portfolio/images/wed-feature.PNG",
        tag: "web",
        link: "https://ronneljunnawedding.com/",
        linkType: "website",
        images: [
            "/portfolio/images/wed-feature.PNG",
            "/portfolio/images/wedding/wed-story.PNG",
            "/portfolio/images/wedding/wed-details.PNG",
            "/portfolio/images/wedding/wed-gallery.PNG",
            "/portfolio/images/wedding/wed-proposal.PNG",
            "/portfolio/images/wedding/wed-prenup.PNG",
            "/portfolio/images/wedding/wed-guest.PNG",
            "/portfolio/images/wedding/wed-orig.PNG",
            "/portfolio/images/wedding/wed-prints.PNG",
            "/portfolio/images/wedding/wed-day.PNG",
            "/portfolio/images/wedding/wed-rsvp.PNG",
        ],
        technologies: ["NextJS", "TailwindCSS", "Typescript", "MySQL", "Supabase", "Cloudinary"],
        role: "Full Stack Developer",
        responsibilities: [
            "Built complete wedding website from scratch",
            "Implemented photo gallery with upload functionality",
            "Created countdown timer and RSVP system",
            "Designed responsive layout for mobile and desktop"
        ]
    },
    {
        project_name: "Better Swing Trader Mobile App",
        project_description: 'Better Swing Trader (BST) is a mobile app designed to help stock swing traders track, analyze, and optimize their trades. It provides clear insights into daily, weekly, and monthly gains and losses, evaluates the effectiveness of trading strategies, and supports risk management by identifying patterns in wins and losses. BST allows traders to monitor individual trades or groups of stocks, refine rules, and compare performance over time, enabling data-driven decisions and continuous improvement. Note: BST is not a trading platform or stock screener; it is a dedicated analytics and performance-tracking tool for swing trading.',
        project_image: "/portfolio/images/bst-feature.png",
        tag: "mobile",
        iosLink: "https://apps.apple.com/us/app/best-swing-trader/id6737796315",
        linkType: "ios",
        images: [
            "/portfolio/images/bst-app/bst-1.webp",
            "/portfolio/images/bst-app/bst-2.webp",
            "/portfolio/images/bst-app/bst-3.webp",
            "/portfolio/images/bst-app/bst-4.webp",
            "/portfolio/images/bst-app/bst-5.webp",
            "/portfolio/images/bst-app/bst-6.webp",
            "/portfolio/images/bst-app/bst-7.webp",
            "/portfolio/images/bst-app/bst-8.webp",
        ],
        technologies: ["React Native", "JavaScript", "MySQL", "AsyncStorage", "React Navigation"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed cross-platform mobile app for iOS and Android",
            "Implemented stock tracking and portfolio management",
            "Created data visualization for gains and losses",
            "Integrated real-time data from API"
        ]
    },
    {
        project_name: "Queue Management System",
        project_description: 'The Queue Management System (QMS) Web Application is a robust and user-friendly platform designed to optimize queue operations for organizations.',
        project_image: "/portfolio/images/tmcsl-qms/tmcsl-qms-9.PNG",
        tag: "web",
        link: "#",
        images: [
            "/portfolio/images/tmcsl-qms/tmcsl-qms.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-1.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-2.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-3.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-4.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-5.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-6.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-7.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-8.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-9.PNG",
            "/portfolio/images/tmcsl-qms/tmcsl-qms-10.PNG",
        ],
        technologies: ["HTML", "CSS", "PHP", "Javascript", "MySQL", "Socket.io"],
        role: "Full Stack Developer",
        responsibilities: [
            "Developed real-time queue management system",
            "Implemented WebSocket for live queue updates",
            "Created admin dashboard for queue control",
            "Built reporting and analytics features",
            "Integrated API"
        ]
    },
    {
        project_name: "Meal Monitoring System",
        project_description: 'Designed to easily claim meals using bar code scanner to efficiently manage and track meal of employees, with reports and filter to easily extract data in excel file.',
        project_image: "/portfolio/images/meal-feature.png",
        tag: "web",
        link: "#",
        images: ["/portfolio/images/meal-feature.png"],
        technologies: ["PHP", "Javascript", "Laravel", "Node.js", "Express", "MySQL"],
        role: "Backend Developer",
        responsibilities: [
            "Developed barcode scanning functionality",
            "Developed reporting system with Excel export",
            "Developed filtering and search features",
        ]
    },
    {
        project_name: "The Medical City South Luzon SOL APP",
        project_description: 'The TMCSL Mobile App streamlines healthcare by allowing patients and professionals to manage appointments, view lab results, and handle billing transactions.',
        project_image: "/portfolio/images/sol-feature.png",
        tag: "mobile",
        link: "#",
        images: [
            "/portfolio/images/sol-feature.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-00.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-1.png",
            "/portfolio/images/tmcsl-app/tmcsl-app.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-2.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-4.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-5.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-6.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-7.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-8.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-9.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-10.png",
            "/portfolio/images/tmcsl-app/tmcsl-app-11.png",

        ],
        technologies: ["Flutter", "Dart", "MySQL", "REST API", "PHP"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed healthcare mobile application using Flutter",
            "Implemented secure authentication and authorization",
            "Created appointment scheduling system",
            "Integrated lab results viewing feature",
            "Integrated billing and payment transaction APIs"
        ]
    },
    {
        project_name: "SSC - For Online SST Customers",
        project_description: 'SSC is a mobile app that enables customers of small retail stores to browse products online and place orders directly from their smartphones. Integrated with the SST point-of-sale system, SSC allows store owners to manage inventory, track sales, and prepare orders efficiently while providing customers a convenient shopping experience from home. The app supports barcode scanning, product information, sales receipts, multi-user access, and device compatibility. By connecting online ordering with in-store POS management, SSC helps small businesses streamline operations, improve customer satisfaction, and gain a competitive edge.',
        project_image: "/portfolio/images/ssc-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.sst_customer",
        linkType: "android",
        images: [
            "/portfolio/images/ssc-app/ssc-1.png",
            "/portfolio/images/ssc-app/ssc-2.png",
            "/portfolio/images/ssc-app/ssc-3.png",
            "/portfolio/images/ssc-app/ssc-4.png",
            "/portfolio/images/ssc-app/ssc-5.png",
        ],
        technologies: ["React Native", "JavaScript", "MySQL", "React Navigation"],
        role: "Mobile Developer",
        responsibilities: [
            "Built customer-facing mobile app for online ordering",
            "Implemented product browsing and search",
            "Created order placement and tracking system",
            "Integrated real-time order notifications"
        ]
    },
    {
        project_name: "SST, Sari Sari iPOS Terminal",
        project_description: 'SST (Sari Sari iPOS Terminal) is a mobile point-of-sale app that transforms smartphones or tablets into a full-featured cash register for small retail or convenience stores. It supports barcode scanning, manual product entry, inventory management, and automated calculations for totals, taxes, and change. The app tracks sales history, generates reports, and allows multi-user support across devices. Designed for ease of use, SST helps businesses streamline transactions, monitor inventory, and improve customer service, making it an efficient and accessible POS solution for small-scale retail operations.',
        project_image: "/portfolio/images/sst-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.sst",
        linkType: "android",
        images: [
            "/portfolio/images/sst-app/sst-1.png",
            "/portfolio/images/sst-app/sst-2.png",
            "/portfolio/images/sst-app/sst-3.png",
            "/portfolio/images/sst-app/sst-4.png",
            "/portfolio/images/sst-app/sst-5.png",
        ],
        technologies: ["React Native", "JavaScript", "MySQL"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed POS system for small retail stores",
            "Implemented barcode scanning functionality",
            "Created inventory management features",
            "Built sales tracking and reporting system",
            "Designed offline-first architecture with sync"
        ]
    },
    {
        project_name: "Cash Expense Tracker",
        project_description: 'Cash Expense Tracker (XPTracker) is a mobile app designed to help users track daily expenses and manage cash spending efficiently. It allows quick entry of expenses, categorization, and viewing summaries by day, week, month, or year, with calendar and detailed report views. The app supports receipt scanning, automatic backups, Excel export, and reminders to ensure no expense is missed. It also allows tracking for multiple users separately or combined, making it ideal for individuals, households, or anyone who wants clear insights into their spending habits.',
        project_image: "/portfolio/images/xpt-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.cxptracker",
        linkType: "android",
        images: [
            "/portfolio/images/xptracker-app/xpt-1.png",
            "/portfolio/images/xptracker-app/xpt-2.png",
            "/portfolio/images/xptracker-app/xpt-3.png",
            "/portfolio/images/xptracker-app/xpt-4.png",
            "/portfolio/images/xptracker-app/xpt-5.png",
            "/portfolio/images/xptracker-app/xpt-6.png",
            "/portfolio/images/xptracker-app/xpt-7.png",
        ],
        technologies: ["React Native", "JavaScript", "AsyncStorage", "Excel Export", "Cloud Backup"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed expense tracking mobile application",
            "Implemented automatic backup functionality",
            "Created expense categorization and tagging",
            "Built export to Excel feature",
            "Designed data visualization for spending patterns"
        ]
    },
    {
        project_name: "Task and Reward Tracker",
        project_description: 'Task and Reward Tracker is a mobile app that allows users to create, assign, and track tasks while rewarding completion with tokens or points. The Primary User (e.g., a parent) can assign tasks to others, set individual values for each task, and monitor completion through notifications, calendars, and task lists. Tokens can be redeemed for monetary value or other rewards, and balances are tracked automatically. The app supports repetitive tasks, multiple users, and real-time updates, making it ideal for families or teams who want a structured and motivating task management system. Dependents receive notifications and can mark tasks as completed, while the Primary User can approve or reject completions, keeping full control over task management and rewards.',
        project_image: "/portfolio/images/trt-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.trt",
        iosLink: "https://apps.apple.com/us/app/task-and-reward-tracker/id1566847771",
        linkType: "both",
        images: [
            "/portfolio/images/trt-app/trt-1.webp",
            "/portfolio/images/trt-app/trt-2.webp",
            "/portfolio/images/trt-app/trt-3.webp",
            "/portfolio/images/trt-app/trt-4.webp",
            "/portfolio/images/trt-app/trt-5.webp",
            "/portfolio/images/trt-app/trt-6.webp",
            "/portfolio/images/trt-app/trt-7.webp",

        ],
        technologies: ["React Native", "JavaScript", "Push Notifications", "AsyncStorage"],
        role: "Mobile Developer",
        responsibilities: [
            "Built task tracking application with timer",
            "Implemented reward system and gamification",
            "Created push notification system",
            "Developed reporting and analytics features"
        ]
    },
    {
        project_name: "Caregiver Assistant",
        project_description: "Caregiver Assistant is a mobile app designed to help caregivers and families record, track, and share vital signs for patients or loved ones. It allows users to log multiple vitals—such as temperature, blood pressure, heart rate, glucose levels, weight, and pain—without providing medical advice. The app supports secure data sharing between caregivers and patients, enabling both parties to enter and view authorized information in real time. With reminders, notifications, and historical trend tracking, Caregiver Assistant helps identify abnormal readings, monitor long-term changes, and support informed follow-ups with healthcare professionals. It supports multiple patients and unlimited vitals, making it suitable for both personal and professional caregiving use.",
        project_image: "/portfolio/images/cga-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.caregiverassistant",
        iosLink: "https://apps.apple.com/us/app/ca-caregiver-assistant/id1608863934",
        linkType: "both",
        images: [
            "/portfolio/images/cga-app/cga-1.webp",
            "/portfolio/images/cga-app/cga-2.webp",
            "/portfolio/images/cga-app/cga-3.webp",
            "/portfolio/images/cga-app/cga-4.webp",
            "/portfolio/images/cga-app/cga-5.webp",
            "/portfolio/images/cga-app/cga-6.webp",
            "/portfolio/images/cga-app/cga-7.webp",
            "/portfolio/images/cga-app/cga-8.webp",
        ],
        technologies: ["React Native", "JavaScript", "Chart Libraries", "AsyncStorage"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed healthcare tracking application",
            "Implemented vital signs recording system",
            "Created data visualization for health trends",
            "Built export and sharing functionality for medical records"
        ]
    },
    {
        project_name: "Client Logger",
        project_description: "Client Logger is a mobile app that enables businesses to quickly and securely log customer check-ins using QR codes or manual entry. It allows users to scan QR codes containing contact details such as name, phone number, and email, or enter information through a form with optional reservation and SMS notification support. Designed for businesses such as restaurants, clinics, and retail stores, the app creates time-stamped visit records that can be used for operational tracking, customer communication, and marketing purposes. Client Logger works across devices without ads, providing a fast and reliable solution for client entry logging and reservation management.",
        project_image: "/portfolio/images/cl-feature.png",
        tag: "mobile",
        link: "#",
        images: [
            "/portfolio/images/cl-app/cl-1.png",
            "/portfolio/images/cl-app/cl-2.png",
            "/portfolio/images/cl-app/cl-3.png",
            "/portfolio/images/cl-app/cl-4.png",
            "/portfolio/images/cl-app/cl-5.png",
            "/portfolio/images/cl-app/cl-6.png",
            "/portfolio/images/cl-app/cl-7.png",
        ],
        technologies: ["React Native", "JavaScript", "SMS API", "Firebase", "QR Code"],
        role: "Mobile Developer",
        responsibilities: [
            "Built client check-in application",
            "Implemented SMS notification system",
            "Created reservation management features",
            "Developed QR code generation and scanning"
        ]
    },
    {
        project_name: "Entry Logger",
        project_description: "Entry Logger is a mobile app that generates a personalized QR code to securely and instantly share user-selected contact information, such as name and phone number. By simply displaying or scanning a QR code, users can log entries and visits without manual forms, ads, or device compatibility issues. The app gives users full control over what information is shared and supports printable QR codes for use anywhere. Designed for both individuals and businesses, Entry Logger enables fast entry logging for establishments such as restaurants, clinics, and retail stores, while also allowing users to track where and when they have visited locations or events.",
        project_image: "/portfolio/images/el-feature.png",
        tag: "mobile",
        androidLink: "https://webcoastserver.com/entrylogger/downloads/",
        linkType: "android",
        images: [
            "/portfolio/images/el-app/el-1.png",
            "/portfolio/images/el-app/el-2.png",
            "/portfolio/images/el-app/el-3.png",
            "/portfolio/images/el-app/el-4.png",
            "/portfolio/images/el-app/el-5.png",
        ],
        technologies: ["React Native", "JavaScript", "QR Code Library", "AsyncStorage"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed QR code generation application",
            "Implemented secure data encoding",
            "Created user information management",
            "Built QR code scanning and validation"
        ]
    },
    {
        project_name: "Budgetfy",
        project_description: "Budgetfy is a mobile app that helps users track budgets, expenses, and income in a simple and intuitive way. It provides daily, weekly, and monthly transaction views, along with visual graphs and reports that offer clear insights into spending habits and financial trends. Designed for quick data entry and ease of use, Budgetfy helps users avoid overspending across all categories with a user-friendly interface suitable for everyday personal finance management.",
        project_image: "/portfolio/images/bf-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=budgetfy.arsoft.com",
        linkType: "android",
        images: [
            "/portfolio/images/budget-app/budget-1.webp",
            "/portfolio/images/budget-app/budget-2.webp",
            "/portfolio/images/budget-app/budget-3.webp",
            "/portfolio/images/budget-app/budget-4.webp",
            "/portfolio/images/budget-app/budget-5.webp",
            "/portfolio/images/budget-app/budget-6.webp",
        ],
        technologies: ["Java", "Android SDK", "SQLite", "MPAndroidChart", "Material Design"],
        role: "Android Developer",
        responsibilities: [
            "Developed native Android budget tracking app",
            "Implemented local database with SQLite",
            "Created data visualization with charts and graphs",
            "Built filtering system (daily/weekly/monthly)",
            "Designed Material Design UI"
        ]
    },
    {
        project_name: "Web Coast Apps",
        project_description: "Web Coast Apps showcases various mobile tracking applications that improve lives through tracking, reporting, and notifications.",
        project_image: "/portfolio/images/wca-web/web-1.PNG",
        tag: "web",
        link: "https://webcoastapps.com/",
        linkType: "website",
        images: [
            "/portfolio/images/wca-web/web-1.PNG",
            "/portfolio/images/wca-web/web-2.PNG",
            "/portfolio/images/wca-web/web-3.PNG",
            "/portfolio/images/wca-web/web-4.PNG",
            "/portfolio/images/wca-web/web-5.PNG",
            "/portfolio/images/wca-web/web-6.PNG",
            "/portfolio/images/wca-web/web-7.PNG",
        ],
        technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
        role: "Frontend Developer",
        responsibilities: [
            "Designed and developed company showcase website",
            "Created responsive layout for all devices",
            "Implemented app presentation sections",
            "Built contact and download sections"
        ]
    },
    {
        project_name: "Performance Evaluation Manager",
        project_description: "Performance Evaluation Manager is a mobile app designed to help managers and employees record performance evaluations between formal review periods. It complements existing company evaluation systems by allowing users to capture ongoing performance records using predefined, weighted questions and categories, making results measurable and easy to compare over time. The app supports both employee evaluations and self-evaluations, enabling users to document achievements, track recurring issues, monitor progress toward goals, and maintain accurate records throughout the year. By aggregating ratings and notes, the app simplifies the creation of fair, data-driven formal reviews. It also includes demo mode and optional remote backup for data security.",
        project_image: "/portfolio/images/pem-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.pem",
        iosLink: "https://apps.apple.com/us/app/performance-evaluation-manager/id1516410882",
        linkType: "both",
        images: [
            "/portfolio/images/pem-app/pem-1.webp",
            "/portfolio/images/pem-app/pem-2.webp",
            "/portfolio/images/pem-app/pem-3.webp",
            "/portfolio/images/pem-app/pem-4.webp",
            "/portfolio/images/pem-app/pem-5.webp",
        ],
        technologies: ["React Native", "JavaScript", "Firebase", "AsyncStorage"],
        role: "Mobile Developer",
        responsibilities: [
            "Built employee evaluation mobile application",
            "Implemented evaluation form system",
            "Created employee performance tracking",
            "Developed reporting and analytics features"
        ]
    },
    {
        project_name: "Tipsee Elite",
        project_description: "TipSee Elite is a fast, ad-free mobile app for tracking tips and income, designed for professionals who earn tips such as servers, delivery drivers, and stylists. It allows users to quickly log cash and card tips, track wages and tip-outs, and view earnings through daily, weekly, monthly, and yearly summaries. Built to run locally for speed and simplicity, the app requires no accounts or cloud setup and includes features such as calendar-based tracking, personalized notes and backgrounds, and automatic data backups. TipSee Elite is fully free and serves as a streamlined entry point to the broader TipSee ecosystem, with seamless data compatibility for upgrading to advanced versions.",
        project_image: "/portfolio/images/te-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.tipseelite",
        iosLink: "https://apps.apple.com/us/app/tipsee-elite/id1535149595",
        linkType: "both",
        images: [
            "/portfolio/images/tip-elite-app/tip-elite-1.webp",
            "/portfolio/images/tip-elite-app/tip-elite-2.webp",
            "/portfolio/images/tip-elite-app/tip-elite-3.webp",
            "/portfolio/images/tip-elite-app/tip-elite-4.webp",
            "/portfolio/images/tip-elite-app/tip-elite-5.webp",
            "/portfolio/images/tip-elite-app/tip-elite-6.webp",
            "/portfolio/images/tip-elite-app/tip-elite-7.webp",
        ],
        technologies: ["React Native", "JavaScript", "Chart Libraries", "AsyncStorage"],
        role: "Mobile Developer",
        responsibilities: [
            "Developed tip tracking application",
            "Implemented data entry and categorization",
            "Created pattern analysis and visualization",
            "Built comparison features (week/month/year)"
        ]
    },
    {
        project_name: "Tipsee",
        project_description: "TipSee is a feature-rich mobile application designed to help tipped workers, gig professionals, and independent contractors track and manage their earnings with ease. Built and continuously improved over more than a decade, the app allows users to log tips, wages, commissions, and expenses in one intuitive platform. TipSee supports multiple jobs, automatic income calculations, detailed weekly, monthly, and yearly reports, and visual insights through charts and trends. Users can customize work schedules, set income goals, receive reminders, and securely back up or export their data for financial analysis. With features such as client-based tip tracking, receipt photo attachments, home screen widgets, and expense tracking, TipSee provides a complete and reliable solution for managing income from multiple sources.",
        project_image: "/portfolio/images/ts-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.wca.tipsee",
        linkType: "android",
        images: [
            "/portfolio/images/tip-app/tip-1.webp",
            "/portfolio/images/tip-app/tip-2.webp",
            "/portfolio/images/tip-app/tip-3.webp",
            "/portfolio/images/tip-app/tip-4.webp",
            "/portfolio/images/tip-app/tip-5.webp",
            "/portfolio/images/tip-app/tip-6.webp",
            "/portfolio/images/tip-app/tip-7.webp",
        ],
        technologies: ["Java", "Android SDK", "SQLite", "MPAndroidChart"],
        role: "Android Developer",
        responsibilities: [
            "Developed comprehensive tip tracking Android app",
            "Implemented local data storage with SQLite",
            "Created charts and graphs for tip analysis",
            "Built export and backup functionality"
        ]
    },
    {
        project_name: "Medicine Scheduler and Tracker",
        project_description: "Medicine Scheduler and Tracker (MST) is a mobile application designed to help users reliably schedule, track, and manage medication intake through timely alarm notifications and clear record-keeping. The app allows users to log what medications were taken—or missed—and view past, current, and upcoming schedules for better daily awareness. \n \n MST focuses strictly on scheduling and tracking. It does not provide medical advice, recommendations, pain management, or data review. All information is user-entered and stored for personal reference only. \n \n Key features include customizable medication reminders (with optional voice alerts), flexible scheduling options (hourly intervals, multiple doses within a time range, or specific times of day such as breakfast, lunch, dinner, or bedtime), and a calendar view showing taken and scheduled medications. A summary dashboard compares actual intake times against scheduled times for the previous, current, and next day. \n \n The app supports unlimited tracking, local data backup, multiple user profiles, and multiple tracking categories—making it suitable for personal use as well as tracking medications for children, pets, or family members. Additional settings allow users to manage notifications, customize UI elements, and access in-app customer support.",
        project_image: "/portfolio/images/mst-feature.png",
        tag: "mobile",
        androidLink: "https://play.google.com/store/apps/details?id=com.medicinest",
        iosLink: "https://apps.apple.com/us/app/medicine-tracker-and-scheduler/id1296334224",
        linkType: "both",
        images: [
            "/portfolio/images/mst-app/mst-1.webp",
            "/portfolio/images/mst-app/mst-2.webp",
            "/portfolio/images/mst-app/mst-3.webp",
            "/portfolio/images/mst-app/mst-4.webp",
            "/portfolio/images/mst-app/mst-5.webp",
            "/portfolio/images/mst-app/mst-6.webp",
        ],
        technologies: ["Java", "Android SDK", "SQLite", "Alarm Manager", "Notifications"],
        role: "Android Developer",
        responsibilities: [
            "Built medicine tracking and scheduling app",
            "Implemented medication reminders and alarms",
            "Created dosage tracking and history",
            "Developed medication schedule management"
        ]
    }
];